import { Component, inject } from '@angular/core';
import { LanguageService } from '../../../core/language.service';

@Component({
  selector: 'app-confidentialite-page',
  standalone: true,
  templateUrl: './confidentialite.html',
  styleUrl: './confidentialite.css'
})
export class ConfidentialitePageComponent {
  l = inject(LanguageService);
  sections = [{"title": "1. Responsable du traitement", "text": "Les informations transmises via le site sont traitées par I-TECH SARL. Pour toute question relative à vos données personnelles ou à l'exercice de vos droits, vous pouvez écrire à contacts@i-techsarl.com."}, {"title": "2. Données susceptibles d'être collectées", "text": "Lorsque vous utilisez le formulaire Contact / Démo, nous pouvons recueillir les informations que vous renseignez : nom, prénom, entreprise, fonction, adresse e-mail professionnelle, téléphone, pays, secteur d'activité, solutions souhaitées et contenu de votre message."}, {"title": "3. Finalités du traitement", "text": "Ces informations sont utilisées pour répondre à votre demande, organiser une démonstration, vous recontacter au sujet de votre projet et assurer le suivi de la relation avec I-TECH."}, {"title": "4. Caractère obligatoire des informations", "text": "Les champs marqués d'un astérisque sont nécessaires au traitement de la demande. Les autres informations sont facultatives. Sans les informations obligatoires, I-TECH peut ne pas être en mesure de donner suite à la demande."}, {"title": "5. Destinataires des données", "text": "Les données sont destinées aux équipes I-TECH habilitées à traiter les demandes commerciales, techniques ou de support. Elles ne sont pas destinées à être vendues à des tiers."}, {"title": "6. Durée de conservation", "text": "Les données sont conservées pendant la durée nécessaire au traitement et au suivi de la demande, puis selon les durées applicables aux obligations administratives, contractuelles ou légales d'I-TECH. Les durées précises doivent être validées par I-TECH avant publication définitive."}, {"title": "7. Sécurité", "text": "I-TECH met en œuvre des mesures organisationnelles et techniques adaptées afin de limiter l'accès non autorisé, la perte, l'altération ou la divulgation des données personnelles."}, {"title": "8. Vos droits", "text": "Vous pouvez contacter I-TECH pour demander l'accès à vos données, leur rectification ou, lorsque les conditions applicables le permettent, leur suppression, leur limitation ou vous opposer à certains traitements."}, {"title": "9. Préférences et stockage local", "text": "Le site peut utiliser le stockage local du navigateur pour mémoriser certaines préférences, notamment la langue choisie. Ces informations servent au fonctionnement et au confort de navigation du site."}, {"title": "10. Mise à jour de la politique", "text": "Cette politique peut évoluer afin de refléter les changements du site, des traitements ou des exigences applicables. La version publiée sur cette page est celle accessible aux visiteurs."}];
}
