import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type Language = "fr" | "en";

const EN: Record<string,string> = {
  "Accueil":"Home", "Solutions":"Solutions", "Secteurs":"Sectors", "Ressources":"Resources", "L'Entreprise":"Company", "Entreprise":"Company",
  "À propos":"About us", "Carrières":"Careers", "Partenaires":"Partners", "Contact & Support":"Contact & Support", "Contact / Démo":"Contact / Demo", "Support Client":"Customer Support",
  "Demander une démo":"Request a demo", "Toutes les solutions":"All solutions", "Tous les secteurs":"All sectors", "Apparence":"Appearance", "Mode clair":"Light mode", "Mode sombre":"Dark mode",
  "Activer le mode clair":"Enable light mode", "Activer le mode sombre":"Enable dark mode",
  "Accélérez la":"Accelerate the", "transformation digitale":"digital transformation", "de votre institution financière.":"of your financial institution.",
  "I-TECH accompagne les banques, établissements de microfinance et entreprises avec des solutions Core Banking, Mobile Banking, Paiement Digital et Transformation Monétique adaptées aux réalités africaines.":"I-TECH supports banks, microfinance institutions and businesses with Core Banking, Mobile Banking, Digital Payment and Card Processing Transformation solutions tailored to African realities.",
  "Découvrir nos solutions":"Discover our solutions", "d'expertise":"of expertise", "Conformité":"Compliance", "Solutions déployées":"Solutions deployed", "en Afrique":"in Africa",
  "Années d'expérience":"Years of experience", "Institutions accompagnées":"Institutions supported", "Pays en Afrique":"Countries in Africa", "Utilisateurs finaux":"End users", "Transactions par an":"Transactions per year",
  "Des résultats qui parlent":"Results that speak for themselves", "Des indicateurs concrets qui reflètent notre accompagnement des institutions financières en Afrique.":"Concrete indicators that reflect our support for financial institutions across Africa.",
  "Gamme ALPHA":"ALPHA Suite", "Des solutions conçues pour les institutions financières modernes":"Solutions designed for modern financial institutions",
  "Une suite logicielle complète pour digitaliser vos opérations, renforcer votre conformité et améliorer l'expérience client.":"A complete software suite to digitize your operations, strengthen compliance and improve the customer experience.",
  "En savoir plus":"Learn more", "Une expertise adaptée à chaque secteur":"Expertise tailored to every sector", "Microfinance":"Microfinance", "Banques":"Banks", "Grandes entreprises":"Large enterprises",
  "Maîtrisez les coûts opérationnels et améliorez l'expérience client.":"Control operating costs and improve the customer experience.", "Modernisez vos systèmes et réinventez vos services digitaux.":"Modernize your systems and reinvent your digital services.", "Automatisez vos processus financiers et de gestion.":"Automate your financial and management processes.",
  "Focus métier":"Business focus", "Diagnostic SI":"IT assessment", "Déploiement":"Deployment", "Accompagnement":"Support",
  "Nos partenaires":"Our partners", "Ils nous font confiance":"They trust us", "Rejoignez plus de":"Join more than", "qui ont choisi I-TECH pour leur transformation digitale.":"that chose I-TECH for their digital transformation.",
  "250 institutions":"250 institutions", "Partenaire I-TECH · institution financière":"I-TECH partner · financial institution", "Visiter le site":"Visit website", "Visiter":"Visit", "Et plus de":"And more than", "250 autres institutions":"250 other institutions", "à travers l'Afrique":"across Africa", "Voir tous nos partenaires":"View all our partners",
  "Nos clients":"Our clients", "Nos Clients":"Our Clients",
  "Pourquoi I-TECH":"Why I-TECH", "Un partenaire technologique de confiance":"A trusted technology partner", "Cliquez sur une fenêtre pour découvrir chaque engagement.":"Click a window to discover each commitment.",
  "Expertise métier":"Industry expertise", "Une connaissance approfondie des métiers financiers.":"In-depth knowledge of financial services.", "Support":"Support", "Une assistance réactive et personnalisée.":"Responsive and personalized assistance.", "Aux normes COBAC, BEAC et internationales.":"Compliant with COBAC, BEAC and international standards.", "Intégration":"Integration", "Compatible avec votre écosystème existant.":"Compatible with your existing ecosystem.", "Sécurité":"Security", "Des données protégées à chaque étape.":"Data protected at every stage.", "Innovation":"Innovation", "Des solutions évolutives pour demain.":"Scalable solutions for tomorrow.", "Ouvrir":"Open", "Fermer":"Close", "Précédent":"Previous", "Suivant":"Next",
  "Prêt à accélérer votre transformation digitale ?":"Ready to accelerate your digital transformation?", "Échangez avec nos experts et découvrez comment I-TECH peut vous accompagner.":"Talk with our experts and discover how I-TECH can support you.", "Demander une démonstration":"Request a demo", "Contactez un expert":"Contact an expert",
  "Tous droits réservés.":"All rights reserved.", "Politique de confidentialité":"Privacy Policy", "Mentions légales":"Legal Notice", "Plan du site":"Sitemap", "Centre de ressources":"Resource Center", "Documentations":"Documentation", "Webinaires":"Webinars",
  "2ème étage, Immeuble CAMCCUL, Rue Pau, Akwa - Douala":"2nd floor, CAMCCUL Building, Rue Pau, Akwa - Douala",
  "Core Banking":"Core Banking", "Collecte Journalière":"Daily Collection", "Digital & Mobile":"Digital & Mobile", "Gestion RH":"HR Management", "Déclaration Bancaire":"Regulatory Reporting", "Génie Logiciel":"Software Engineering",
  "Centralisez toutes vos opérations bancaires sur une plateforme fiable et évolutive.":"Centralize all your banking operations on a reliable and scalable platform.",
  "Simplifiez la collecte et le suivi de vos agents collecteurs sur le terrain.":"Simplify field collection and the monitoring of your collection agents.",
  "Offrez une expérience bancaire digitale fluide et sécurisée.":"Deliver a seamless and secure digital banking experience.",
  "Gérez efficacement vos talents et processus administratifs.":"Efficiently manage your talent and administrative processes.",
  "La plateforme bancaire qui centralise toutes vos opérations.":"The banking platform that centralizes all your operations.",
  "Digitalisez vos encaissements et rapprochez-vous de vos clients.":"Digitize your collections and get closer to your customers.",
  "Paie & déclarations":"Payroll & declarations", "Congés & absences":"Leave & absences", "Évaluations & reporting":"Performance reviews & reporting",
  "Automatisez vos déclarations réglementaires et assurez votre conformité.":"Automate your regulatory reporting and ensure compliance.",
  "Automatisez vos déclarations et restez conforme en continu.":"Automate your declarations and maintain continuous compliance.", "Déclarations COBAC":"COBAC declarations", "Contrôles & validations":"Controls & validations",
  "Concevez des solutions logicielles adaptées à votre métier":"Build software solutions tailored to your business", "Développez des plateformes web, mobiles et métiers robustes, évolutives et sécurisées.":"Develop robust, scalable and secure web, mobile and business platforms.", "Applications Web":"Web Applications", "Applications Mobiles":"Mobile Applications", "API & Intégrations":"APIs & Integrations",
  "Comptes, prêts & épargne":"Accounts, loans & savings", "Multi-agences & devises":"Multi-branch & multi-currency", "Reporting réglementaire":"Regulatory reporting",
  "Gestion des collecteurs":"Collector management", "Suivi en temps réel":"Real-time monitoring", "Commissions automatisées":"Automated commissions",
  "Mobile Banking":"Mobile Banking", "Portails clients":"Customer portals", "Paiements digitaux":"Digital payments",
  "Gérez vos talents, la paie et l'administration du personnel.":"Manage your talent, payroll and personnel administration.",
  "Automatisez vos déclarations réglementaires et sécurisez votre conformité.":"Automate your regulatory reporting and secure your compliance.",
  "Concevez des applications métier sur mesure, robustes et évolutives.":"Build custom business applications that are robust and scalable.",
  "Microfinances":"Microfinance institutions", "Banques Commerciales":"Commercial Banks", "Grandes Entreprises":"Large Enterprises",

  // Solutions — overview and detail pages
  "Gamme ALPHA · Solutions I-TECH":"ALPHA Suite · I-TECH Solutions",
  "Parler à un expert":"Talk to an expert", "Solution ALPHA":"ALPHA Solution", "Fonctionnalités clés":"Key features", "Captures d’écran":"Screenshots", "Voir plus de captures":"View more screenshots", "Échange avec nos experts":"Talk with our experts",
  "Des solutions innovantes au service de l'accélération de votre transformation digitale":"Innovative solutions to accelerate your digital transformation",
  "Découvrez la suite ALPHA et les solutions I-TECH : des outils performants dédiés aux banques, aux institutions de microfinance et aux entreprises en quête d'efficacité.":"Discover the ALPHA Suite and I-TECH solutions: powerful tools designed for banks, microfinance institutions and businesses seeking greater efficiency.",
  "Support disponible":"Support available", "Présence régionale":"Regional presence",
  "Un écosystème intégré pour couvrir tous vos besoins métier":"An integrated ecosystem covering all your business needs",
  "Gestion complète des opérations bancaires et financières":"Complete management of banking and financial operations",
  "Digitalisez vos encaissements et rapprochements terrain":"Digitize your field collections and reconciliation processes",
  "Services digitaux & mobiles pour vous démarquer de vos concurrents":"Digital and mobile services that help you stand out from competitors",
  "Gérez efficacement vos talents, la paie et l'administration du personnel":"Efficiently manage talent, payroll and personnel administration",
  "Déclarations réglementaires et reporting bancaire":"Regulatory declarations and banking reporting",
  "Une suite complète et intégrée":"A complete and integrated suite", "Nos solutions":"Our solutions",
  "Prêt à transformer votre institution ?":"Ready to transform your institution?", "Échangez avec nos experts et découvrez la solution la plus adaptée à vos besoins.":"Talk with our experts and discover the solution best suited to your needs.",
  "Gérez les comptes, crédits, épargne, opérations de caisse et reporting depuis une plateforme unique, sécurisée et évolutive.":"Manage accounts, loans, savings, teller operations and reporting from one secure, scalable platform.",
  "Une architecture complète et intégrée":"A complete and integrated architecture", "Gestion bancaire complète":"Complete banking management", "Gestion des comptes":"Account management", "Gestion du crédit":"Loan management", "Gestion de l'épargne":"Savings management", "Gestion des agences":"Branch management", "Comptabilité intégrée et reporting":"Integrated accounting and reporting", "Alpha Comptabilité":"Alpha Accounting", "Alpha Monétique":"Alpha Card Management", "Émission de cartes et transactions":"Card issuance and transactions",
  "Créez et administrez comptes courants, épargne et comptes professionnels depuis un référentiel client unique.":"Create and manage current, savings and business accounts from a single customer repository.",
  "Instruisez, octroyez et suivez les crédits avec échéanciers, garanties et relances automatiques.":"Process, grant and monitor loans with schedules, guarantees and automated reminders.",
  "Proposez des produits d'épargne souples, avec intérêts calculés automatiquement et relevés détaillés.":"Offer flexible savings products with automatically calculated interest and detailed statements.",
  "Pilotez votre réseau multi-agences : caisses, utilisateurs, habilitations et consolidations.":"Manage your multi-branch network: tellers, users, permissions and consolidations.",
  "Exploitez tableaux de bord et états de pilotage pour décider vite, sur des données fiables.":"Use dashboards and management reports to make faster decisions based on reliable data.",
  "Centralisation des opérations":"Centralized operations", "Conformité réglementaire":"Regulatory compliance", "Efficacité opérationnelle":"Operational efficiency", "Meilleure prise de décision":"Better decision-making", "Expérience client améliorée":"Improved customer experience", "Découvrez comment ALPHA peut transformer la gestion de votre institution.":"Discover how ALPHA can transform the management of your institution.",
  "I-Collect simplifie la collecte terrain, sécurise les opérations et améliore le suivi des collecteurs en temps réel.":"I-Collect simplifies field collection, secures operations and improves real-time monitoring of collectors.", "Une solution complète pour la collecte terrain":"A complete solution for field collection", "Collecte sur le terrain":"Field collection", "Gestion des collecteurs et tournées":"Collector and route management", "Encaissements sécurisés (POS & Mobile)":"Secure collections (POS & Mobile)", "Reçus électroniques instantanés":"Instant electronic receipts", "Synchronisation en temps réel":"Real-time synchronization", "Rapprochement comptable":"Accounting reconciliation", "Suivi & contrôle des équipes":"Team monitoring & control", "Application épargnant: MyCollect":"Saver app: MyCollect", "Suivi en temps réel des activités":"Real-time activity monitoring", "Meilleur contrôle des équipes":"Better team control", "Gain de temps et productivité":"Time savings and productivity", "Sécurité renforcée":"Enhanced security", "Augmentation de la rentabilité":"Increased profitability", "Digitalisez votre collecte journalière dès aujourd'hui.":"Digitize your daily collection today.",
  "Alpha Mobile Banking et les services digitaux I-TECH permettent à vos clients d'accéder à leurs services 24h/24 et 7j/7.":"Alpha Mobile Banking and I-TECH digital services give your customers access to their services 24/7.", "Une expérience digitale complète":"A complete digital experience", "Portails Clients":"Customer Portals", "Paiements Digitaux":"Digital Payments", "Notifications & Alertes":"Notifications & Alerts", "Sécurité Avancée":"Advanced Security", "Consultation de comptes":"Account overview", "Virements & transferts":"Transfers & remittances", "Paiement de factures & marchands":"Bill & merchant payments", "Historique des opérations":"Transaction history", "Géolocalisation des agences":"Branch geolocation", "Notifications push & SMS":"Push & SMS notifications", "Authentification forte":"Strong authentication", "Fidélisation des clients":"Customer loyalty", "Réduction des coûts opérationnels":"Reduced operating costs", "Disponibilité 24/7":"24/7 availability", "Image moderne et innovante":"Modern and innovative image", "Croissance des usages digitaux":"Growth in digital usage", "Offrez le meilleur de la banque digitale à vos clients.":"Give your customers the best of digital banking.",
  "Alpha RH centralise la gestion des ressources humaines pour gagner en efficacité et rester conforme.":"Alpha HR centralizes human resources management to improve efficiency and maintain compliance.", "Gestion du personnel":"Personnel management", "Paie & déclarations sociales":"Payroll & social declarations", "Gestion des congés & absences":"Leave & absence management", "Évaluations & entretiens":"Performance reviews & interviews", "Reporting RH":"HR reporting", "Les bénéfices pour votre organisation":"Benefits for your organization", "Automatisation des processus":"Process automation", "Conformité légale":"Legal compliance", "Meilleure gestion des talents":"Better talent management", "Réduction des erreurs":"Reduced errors", "Décisions RH éclairées":"Better-informed HR decisions", "Optimisez la gestion de vos ressources humaines.":"Optimize your human resources management.",
  "Alpha Déclaration Bancaire génère automatiquement vos états réglementaires et vos reportings dans les formats exigés par les régulateurs.":"Alpha Regulatory Reporting automatically generates your regulatory statements and reports in the formats required by regulators.", "États réglementaires":"Regulatory statements", "Génération automatique des états":"Automatic statement generation", "Conformité assurée":"Assured compliance", "Gain de temps significatif":"Significant time savings", "Réduction des risques":"Reduced risk", "Traçabilité complète":"Complete traceability", "Archivage sécurisé":"Secure archiving", "Simplifiez vos déclarations et restez conforme.":"Simplify your regulatory declarations and stay compliant.",
  "Nous développons des plateformes web, mobiles et métiers robustes, évolutives et sécurisées pour accompagner la croissance de votre organisation.":"We develop robust, scalable and secure web, mobile and business platforms to support your organization's growth.", "Gestion Documentaire":"Document Management", "Solutions Sur Mesure":"Custom Solutions", "Pourquoi choisir I-TECH ?":"Why choose I-TECH?", "Expertise Métier":"Industry Expertise", "Équipe Locale":"Local Team", "Évolutivité":"Scalability", "Concevez une solution logicielle adaptée à votre métier.":"Design a software solution tailored to your business.",
  "Les bénéfices pour votre institution":"Benefits for your institution", "Tableau de bord":"Dashboard", "Comptes":"Accounts", "Reporting":"Reporting"
,

  // Sectors — overview and detail pages
  "Secteurs / Cibles":"Sectors / Target Markets", "Secteurs · Cibles":"Sectors · Target Markets", "Secteur · Microfinances":"Sector · Microfinance", "Secteur · Banques Commerciales":"Sector · Commercial Banks", "Secteur · Grandes Entreprises":"Sector · Large Enterprises",
  "Des solutions adaptées à votre secteur d'activité":"Solutions tailored to your industry", "Découvrez comment I-TECH accompagne les institutions financières et les entreprises grâce à des solutions spécialisées.":"Discover how I-TECH supports financial institutions and businesses with specialized solutions.", "Trouver ma solution":"Find my solution", "Choisissez votre secteur":"Choose your sector", "Nous comprenons vos enjeux métier et proposons des solutions adaptées à vos défis quotidiens.":"We understand your business challenges and provide solutions tailored to your day-to-day needs.", "Découvrir":"Discover",
  "Méthode":"Method", "Notre approche":"Our approach", "La section « Cibles » permet de parler directement aux besoins des différents types de clients. Contrairement à la section « Solutions » qui présente les produits, cette section présente les problématiques métiers de chaque secteur et les solutions adaptées. Cette approche permet aux visiteurs de s'identifier rapidement et améliore fortement la conversion.":"The ‘Target Markets’ section directly addresses the needs of different client types. Unlike the ‘Solutions’ section, which presents products, this section focuses on each sector's business challenges and the solutions best suited to them. This approach helps visitors quickly identify with their needs and significantly improves conversion.",
  "Centré sur vos métiers":"Focused on your business", "Nous comprenons vos défis et parlons votre langage.":"We understand your challenges and speak your language.", "Solutions adaptées":"Tailored solutions", "Des réponses concrètes à vos problématiques.":"Practical answers to your challenges.", "Résultats concrets":"Tangible results", "Des bénéfices mesurables pour votre organisation.":"Measurable benefits for your organization.", "Accompagnement":"Support", "Un support expert à chaque étape de votre projet.":"Expert support at every stage of your project.",
  "Vous ne savez pas par où commencer ?":"Not sure where to start?", "Décrivez-nous votre activité, nous vous orientons vers le secteur et les solutions adaptés.":"Tell us about your business and we will guide you toward the right sector and solutions.",
  "Gestion des opérations, conformité COBAC, collecte terrain et digitalisation.":"Operations management, COBAC compliance, field collection and digitalization.", "Core Banking, monétique, digital banking et intégration.":"Core Banking, card processing, digital banking and integration.", "RH, comptabilité, GED et développement spécifique.":"HR, accounting, document management and custom development.",
  "Les solutions conçues pour les établissements de microfinance":"Solutions designed for microfinance institutions", "Optimisez la gestion de votre institution grâce à des outils conformes aux exigences réglementaires et adaptés aux réalités du terrain.":"Optimize your institution's management with tools that meet regulatory requirements and are adapted to field realities.", "Vos problématiques au quotidien":"Your day-to-day challenges", "NOS SOLUTIONS":"OUR SOLUTIONS", "Des solutions adaptées pour simplifier la gestion de vos activités financières.":"Solutions designed to simplify the management of your financial activities.",
  "Gestion des crédits":"Loan management", "Gérez vos crédits, échéances et suivis en toute simplicité.":"Manage loans, repayment schedules and follow-up with ease.", "Gestion de l'épargne":"Savings management", "Optimisez la collecte et la gestion de l'épargne de vos clients.":"Optimize the collection and management of your customers' savings.", "Simplifiez la collecte et le suivi des opérations quotidiennes.":"Simplify collection and the monitoring of daily operations.", "Conformité COBAC":"COBAC compliance", "Assurez la conformité de vos opérations avec les normes COBAC.":"Ensure your operations comply with COBAC standards.",
  "MAPPING BESOINS":"NEEDS MAPPING", "Nos solutions recommandées":"Our recommended solutions", "Des solutions adaptées à chaque besoin pour accélérer":"Solutions tailored to every need to accelerate", " votre performance financière.":" your financial performance.", "BESOIN":"NEED", "SOLUTION":"SOLUTION", "Plus de":"More", "performances":"performance", "ensemble !":"together!", "Des solutions fiables pour un avenir plus solide.":"Reliable solutions for a stronger future.",
  "Une plateforme centralisée pour une gestion bancaire complète et sécurisée.":"A centralized platform for complete and secure banking management.", "La solution au cœur de votre banque.":"The solution at the heart of your bank.", "Paiements":"Payments", "Des paiements rapides, sûrs et adaptés à tous vos canaux.":"Fast, secure payments tailored to all your channels.", "La fluidité de vos transactions.":"Seamless transactions.", "Digital":"Digital", "Des services digitaux innovants pour une meilleure expérience client.":"Innovative digital services for a better customer experience.", "Votre banque, partout et à tout moment.":"Your bank, anywhere and anytime.", "Une gestion simplifiée et conforme de vos déclarations réglementaires.":"Simplified and compliant management of your regulatory reporting.", "Conformité et sérénité.":"Compliance with peace of mind.",
  "Réduction des tâches manuelles":"Reduced manual tasks", "Contrôle renforcé":"Stronger controls", "Conformité réglementaire":"Regulatory compliance", "Digitalisation du réseau":"Network digitalization", "Projet CEPAC":"CEPAC Project", "Déploiement d'Alpha Microfinance":"Alpha Microfinance deployment", "Projet EMF":"MFI Project", "Digitalisation de la collecte terrain":"Digitalization of field collection", "Témoignage client":"Client testimonial", "I-TECH a transformé notre manière de travailler.":"I-TECH transformed the way we work.", "Directeur Général":"Chief Executive Officer", "Prêt à transformer votre institution ?":"Ready to transform your institution?", "Découvrez comment nos solutions peuvent répondre à vos défis.":"Discover how our solutions can address your challenges.",
  "Accélérez la transformation digitale de votre banque":"Accelerate your bank's digital transformation", "Des solutions robustes pour moderniser les opérations bancaires, les paiements et les services digitaux.":"Robust solutions to modernize banking operations, payments and digital services.", "Vos enjeux bancaires":"Your banking challenges", "Monétique":"Card processing", "Digital Banking":"Digital Banking", "Intégration API":"API integration", "Centralisation des opérations":"Centralized operations", "Réduction des coûts":"Reduced costs", "Expérience client améliorée":"Improved customer experience", "Sécurité renforcée":"Enhanced security", "Architecture bancaire":"Banking architecture", "Migration bancaire":"Banking migration", "Modernisation du SI bancaire":"Banking information system modernization", "Déploiement monétique":"Card processing platform deployment", "Mise en place de la plateforme monétique":"Implementation of the card processing platform", "Un partenaire fiable pour notre projet stratégique.":"A reliable partner for our strategic project.", "DSI Banque":"Bank CIO", "Construisons ensemble votre banque digitale":"Let's build your digital bank together", "Nos experts vous accompagnent à chaque étape de votre transformation.":"Our experts support you at every stage of your transformation.",
  "Des solutions sur mesure pour les grandes entreprises":"Tailored solutions for large enterprises", "Optimisez vos processus, gérez vos talents et sécurisez vos informations.":"Optimize your processes, manage your talent and secure your information.", "Vos enjeux métiers":"Your business challenges", "Gestion des Ressources Humaines":"Human Resources Management", "Comptabilité & Finance":"Accounting & Finance", "Gestion Électronique des Documents":"Electronic Document Management", "Développement Spécifique":"Custom Development", "Comptabilité":"Accounting", "Développement":"Development", "Productivité accrue":"Increased productivity", "Meilleure traçabilité":"Improved traceability", "Sécurité des données":"Data security", "Adaptabilité et évolutivité":"Adaptability and scalability", "Projet RH":"HR Project", "Digitalisation des processus RH":"Digitalization of HR processes", "Projet Comptabilité":"Accounting Project", "Automatisation comptable":"Accounting automation", "Des solutions adaptées à nos besoins spécifiques.":"Solutions tailored to our specific needs.", "Directeur Financier":"Chief Financial Officer", "Digitalisez vos processus, gagnez en performance":"Digitalize your processes and improve performance", "Nos solutions s'adaptent à votre organisation.":"Our solutions adapt to your organization.",
  "Les bénéfices pour votre banque":"Benefits for your bank", "Les bénéfices pour votre entreprise":"Benefits for your business", "Gestion EMF":"MFI management", "Collecte":"Collection", "Mobile":"Mobile", "Déclarations":"Reporting", "Solutions Sur Mesure":"Custom Solutions", "Sécurité des données":"Data security",

  // Company — main page, About, Careers, Partners
  "Construisons l'avenir de la transformation digitale en Afrique Centrale":"Building the future of digital transformation in Central Africa",
  "Découvrir notre histoire":"Discover our story", "Rejoindre notre équipe":"Join our team", "Clients accompagnés":"Clients supported", "Support technique":"Technical support",
  "Notre univers":"Our world", "Découvrez l'univers I-TECH":"Discover the I-TECH world", "À PROPOS":"ABOUT US", "CARRIÈRES":"CAREERS", "PARTENAIRES":"PARTNERS",
  "Découvrez notre histoire, notre mission, nos valeurs et notre équipe.":"Discover our history, mission, values and team.", "Voir les opportunités":"View opportunities", "Découvrez les organisations et technologies qui collaborent avec nous.":"Discover the organizations and technologies that collaborate with us.", "Voir nos partenaires":"View our partners",
  "Restez informé de nos actualités":"Stay up to date with our news", "Recevez nos dernières actualités, événements et ressources.":"Receive our latest news, events and resources.", "Votre adresse e-mail":"Your email address", "S'abonner":"Subscribe",
  "À propos de I-TECH":"About I-TECH", "Notre parcours":"Our journey", "Création de l'entreprise":"Company founded", "Lancement de la suite ALPHA":"Launch of the ALPHA Suite", "Expansion régionale":"Regional expansion", "La zone CEMAC":"The CEMAC region", "Plus de 250 institutions":"More than 250 institutions", "institutions accompagnées":"institutions supported", "Aujourd'hui":"Today", "Leader des solutions":"Leading provider of solutions", "technologiques pour les institutions financières":"technology solutions for financial institutions",
  "Notre raison d'être":"Our purpose", "Notre mission":"Our mission", "Accompagner les acteurs économiques dans leur transformation digitale grâce à des solutions fiables, innovantes et adaptées aux réalités africaines.":"Support economic players in their digital transformation with reliable, innovative solutions tailored to African realities.",
  "Nos valeurs":"Our values", "Nous anticipons les évolutions du marché grâce à la recherche et au développement.":"We anticipate market developments through research and development.", "Flexibilité":"Flexibility", "Nous adaptons nos solutions à chaque contexte et besoin spécifique de nos clients.":"We adapt our solutions to each context and to our clients' specific needs.", "Dynamisme":"Dynamism", "Nous favorisons l'amélioration continue et l'excellence opérationnelle.":"We foster continuous improvement and operational excellence.",
  "Notre équipe":"Our team", "Direction":"Management", "Pilotage stratégique":"Strategic leadership", "Experts métiers":"Business experts", "Conseil financier":"Financial consulting", "Développeurs":"Developers", "Génie logiciel":"Software engineering", "Consultants":"Consultants", "Accompagnement":"Support", "Assistance client":"Customer assistance", "Voir toute l'équipe":"View the full team",
  "Pourquoi nous choisir":"Why choose us", "Support local":"Local support", "Une équipe disponible 24/7 pour vous accompagner.":"A team available 24/7 to support you.", "Protection maximale de vos données et opérations.":"Maximum protection for your data and operations.", "De l'analyse à la mise en production et au-delà.":"From analysis to production and beyond.", "Des solutions modernes et évolutives.":"Modern and scalable solutions.",
  "Rejoignez l'équipe I-TECH":"Join the I-TECH team", "Participez à la conception de solutions financières de demain.":"Help design the financial solutions of tomorrow.", "Environnement collaboratif":"Collaborative environment", "Évolution professionnelle":"Career development", "Projets stimulants":"Challenging projects", "Impact concret":"Tangible impact",
  "Recrutement":"Recruitment", "Nos opportunités":"Our opportunities", "Rejoignez une équipe passionnée par l'innovation et impactez le futur.":"Join a team passionate about innovation and help shape the future.", "Développeur Full Stack":"Full Stack Developer", "Yaoundé, Cameroun · CDI":"Yaoundé, Cameroon · Permanent contract", "Développer des applications web et mobiles robustes et évolutives.":"Develop robust and scalable web and mobile applications.", "Consultant Fonctionnel":"Functional Consultant", "Recueillir les besoins, analyser les processus métiers et accompagner nos clients.":"Gather requirements, analyze business processes and support our clients.", "Administrateur Systèmes":"Systems Administrator", "Assurer l'administration, la disponibilité et la sécurité des infrastructures.":"Ensure infrastructure administration, availability and security.", "Support Technique":"Technical Support", "Assurer le support de niveau 1 et 2 auprès de nos utilisateurs.":"Provide level 1 and level 2 support to our users.", "Voir l'offre":"View position", "Voir toutes les opportunités":"View all opportunities",
  "Pourquoi travailler chez I-TECH ?":"Why work at I-TECH?", "Apprentissage continu":"Continuous learning", "Formations et montée en compétences régulières.":"Regular training and skills development.", "Équilibre vie pro / perso":"Work-life balance", "Horaires flexibles et bien-être au quotidien.":"Flexible hours and everyday well-being.", "Culture d'équipe":"Team culture", "Esprit d'entraide et bienveillance au quotidien.":"A culture of mutual support and respect every day.", "Rémunération attractive":"Competitive compensation", "Packages compétitifs et avantages sociaux.":"Competitive packages and employee benefits.", "Vous ne trouvez pas le poste idéal ?":"Can't find the right position?", "Envoyez-nous votre candidature spontanée.":"Send us your unsolicited application.", "Postuler spontanément":"Submit an application",
  "Des collaborations solides pour des solutions performantes et durables.":"Strong partnerships for high-performing and sustainable solutions.", "Écosystème":"Ecosystem", "Partenaires technologiques":"Technology partners", "Nous collaborons avec des éditeurs et fournisseurs de technologies de premier plan.":"We collaborate with leading technology vendors and providers.", "Coopération":"Cooperation", "Partenaires institutionnels":"Institutional partners", "Nous travaillons avec des organisations et institutions pour promouvoir l'innovation et la croissance.":"We work with organizations and institutions to promote innovation and growth.", "Construisons ensemble":"Let's build together", "Devenez partenaire":"Become a partner", "Vous souhaitez collaborer avec I-TECH ? Construisons ensemble des solutions innovantes et créons de la valeur pour nos clients.":"Would you like to collaborate with I-TECH? Let's build innovative solutions together and create value for our clients.", "Nous contacter":"Contact us"
,
  "Depuis plus de 19 ans, I-TECH accompagne les institutions financières et les entreprises dans leur modernisation grâce à des solutions innovantes et adaptées à leur environnement.":"For more than 19 years, I-TECH has supported financial institutions and businesses in their modernization with innovative solutions tailored to their environment.",
  "19 ans d'innovation au service de la transformation digitale en Afrique Centrale.":"19 years of innovation serving digital transformation in Central Africa.",
  "19 ans d'expérience au service de nos clients.":"19 years of experience serving our clients.",

  // Resources — news and newsletter
  "Actualités":"News", "Veille I-TECH":"I-TECH Insights", "Actualités & Ressources":"News & Resources",
  "Restez informés des dernières tendances, projets et innovations du secteur financier.":"Stay informed about the latest trends, projects and innovations in the financial sector.",
  "Filtrer les ressources":"Filter resources", "Tous les articles":"All articles", "Produits":"Products", "Projets":"Projects", "Conseils":"Insights", "Événements":"Events",
  "I-COLLECT : La solution qui révolutionne la collecte journalière":"I-COLLECT: The solution revolutionizing daily collection",
  "La collecte journalière constitue l'un des services phares des établissements de microfinance (EMF). Ce dispositif permet aux particuliers, sur leurs lieux d'activité ou de résidence, de constituer une épargne de manière progressive et quotidienne…":"Daily collection is one of the flagship services offered by microfinance institutions (MFIs). It enables individuals to build savings progressively and daily, at their place of business or residence…",
  "Migration du système d'information de la CEPAC vers la plateforme ALPHA : une transition prometteuse":"Migration of CEPAC's information system to the ALPHA platform: a promising transition",
  "Depuis plusieurs semaines, la CEPAC-Solidarité a engagé un processus de rénovation de son core banking system, conçu pour objectif l'intégration de la plateforme ALPHA au sein de son système d'information.":"For several weeks, CEPAC-Solidarité has been modernizing its core banking system with the goal of integrating the ALPHA platform into its information system.",
  "Open Banking : vers un écosystème financier plus ouvert et collaboratif":"Open Banking: toward a more open and collaborative financial ecosystem",
  "L'Open Banking transforme profondément la manière dont les institutions financières interagissent entre elles et avec leurs clients. Grâce aux API, les services deviennent plus fluides…":"Open Banking is profoundly changing how financial institutions interact with one another and with their customers. APIs are making services more seamless…",
  "Publié le 4 novembre 2021":"Published November 4, 2021", "Publié le 25 octobre 2021":"Published October 25, 2021", "Par Maguy Laurence MATALA":"By Maguy Laurence MATALA", "Par M.L. MATALA":"By M.L. MATALA", "Par Équipe I-TECH":"By the I-TECH Team",
  "Lire l'article":"Read article", "Aucun article dans cette catégorie":"No articles in this category", "Revenez prochainement pour découvrir de nouvelles ressources.":"Check back soon to discover new resources.", "Page suivante":"Next page",
  "Merci pour votre inscription !":"Thank you for subscribing!", "Ne manquez aucune actualité":"Don't miss any news", "Vous recevrez nos prochaines actualités et ressources.":"You will receive our latest news and resources.", "Abonnez-vous à notre newsletter et recevez nos dernières actualités et ressources.":"Subscribe to our newsletter and receive our latest news and resources.", "Votre adresse email":"Your email address"
,

  // Contact & Support — contact and demo pages
  "Comment pouvons-nous vous aider ?":"How can we help you?",
  "Nos équipes commerciales, techniques et support sont à votre disposition pour répondre à vos besoins.":"Our sales, technical and support teams are available to meet your needs.",
  "CONTACT / DÉMO":"CONTACT / DEMO", "SUPPORT CLIENT":"CUSTOMER SUPPORT",
  "Découvrez nos solutions et échangez avec nos experts pour trouver la solution adaptée à vos besoins.":"Discover our solutions and talk with our experts to find the solution that best meets your needs.",
  "Obtenez une assistance technique, ouvrez un ticket ou consultez nos ressources d'aide.":"Get technical assistance, open a ticket or browse our help resources.",
  "Accéder au support":"Access support", "Informations de contact":"Contact information", "Téléphone":"Phone", "Adresse":"Address", "Horaires":"Business hours",
  "Lun - Ven : 8h00 - 17h00":"Mon - Fri: 8:00 AM - 5:00 PM", "Réponse sous 24h":"Response within 24 hours", "Cameroun":"Cameroon",
  "Besoin d'une réponse rapide ?":"Need a quick response?", "Notre équipe vous rappelle sous 24h ouvrées.":"Our team will call you back within 24 business hours.", "Être rappelé(e)":"Request a callback",
  "Envoyez-nous votre demande en quelques secondes. Elle sera transmise directement à notre équipe.":"Send us your request in a few seconds. It will be forwarded directly to our team.",
  "Nom complet":"Full name", "Votre demande":"Your request", "Envoi en cours…":"Sending…",
  "Votre demande a bien été envoyée. Notre équipe vous répondra dans les meilleurs délais.":"Your request has been sent successfully. Our team will get back to you as soon as possible.",
  "Impossible d'envoyer votre demande. Veuillez réessayer ou écrire à contacts@i-techsarl.com.":"Unable to send your request. Please try again or email contacts@i-techsarl.com.",
  "Votre numéro de téléphone":"Your phone number", "Me rappeler":"Call me back", "Merci ! Un conseiller vous rappelle sous 24h ouvrées.":"Thank you! An advisor will call you back within 24 business hours.",
  "Planifiez une démonstration avec nos experts":"Schedule a demo with our experts", "Découvrez comment les solutions I-TECH peuvent accompagner la croissance et la transformation digitale de votre organisation.":"Discover how I-TECH solutions can support your organization's growth and digital transformation.",
  "Accompagnement des banques commerciales dans leur transformation digitale.":"Supporting commercial banks in their digital transformation.", "Solutions complètes adaptées aux établissements de microfinance (EMF).":"Comprehensive solutions tailored to microfinance institutions (MFIs).", "Entreprises":"Businesses", "Solutions RH, GED, comptabilité et développement spécifique.":"HR, document management, accounting and custom development solutions.",
  "Alpha Monétique":"Alpha Card Management", "Alpha Comptabilité":"Alpha Accounting", "Déclaration Bancaire":"Regulatory Reporting",
  "Gabon":"Gabon", "Congo":"Congo", "Tchad":"Chad", "République Centrafricaine":"Central African Republic", "Guinée Équatoriale":"Equatorial Guinea", "Côte d'Ivoire":"Côte d'Ivoire", "Sénégal":"Senegal", "RD Congo":"DR Congo", "Autre":"Other",
  "Banque commerciale":"Commercial bank", "Grande entreprise":"Large enterprise", "Assurance":"Insurance", "Administration":"Public administration",
  "Lun - Ven : 8h00 - 17h00":"Mon - Fri: 8:00 AM - 5:00 PM",
  "Demande envoyée !":"Request sent!", "Merci pour votre intérêt. Un expert I-TECH vous contactera sous 24h ouvrées pour planifier votre démonstration.":"Thank you for your interest. An I-TECH expert will contact you within 24 business hours to schedule your demo.", "Envoyer une autre demande":"Send another request",
  "Nom":"Last name", "Prénom":"First name", "Organisation / Société":"Organization / Company", "Fonction":"Job title", "Email professionnel":"Business email", "Pays":"Country", "Sélectionnez votre pays":"Select your country", "Secteur d'activité":"Industry", "Sélectionnez votre secteur":"Select your industry", "Banques commerciales":"Commercial banks", "Grandes entreprises":"Large enterprises", "Précisez votre secteur d'activité":"Specify your industry", "Ex. : Télécommunications, santé, industrie…":"E.g.: Telecommunications, healthcare, industry…",
  "Solution(s) souhaitée(s)":"Solution(s) of interest", "Sélectionnez une ou plusieurs solutions dans la liste à droite":"Select one or more solutions from the list on the right", "Votre message (facultatif)":"Your message (optional)", "Décrivez brièvement vos besoins ou votre projet…":"Briefly describe your needs or project…", "J'accepte la politique de confidentialité.":"I accept the privacy policy.", "Envoyer ma demande":"Send my request",
  "Je suis intéressé par :":"I'm interested in:", "Contact rapide":"Quick contact", "Questions fréquentes":"Frequently asked questions",
  "Combien coûte une solution I-TECH ?":"How much does an I-TECH solution cost?", "Le coût dépend de la solution choisie, du nombre d'agences et d'utilisateurs, ainsi que des modules activés. Nous vous remettons un devis personnalisé après un premier échange.":"The cost depends on the selected solution, the number of branches and users, and the modules enabled. We provide a personalized quote after an initial discussion.",
  "Combien de temps dure un projet ?":"How long does a project take?", "Un déploiement standard dure entre 6 et 16 semaines selon le périmètre, la reprise des données et les intégrations à réaliser.":"A standard deployment takes between 6 and 16 weeks depending on the scope, data migration and required integrations.",
  "Comment se déroule une démonstration ?":"How does a demo work?", "Un expert I-TECH vous présente la solution en visioconférence ou dans vos locaux, sur la base de vos cas d'usage, pendant environ 45 minutes.":"An I-TECH expert presents the solution by video conference or at your premises, based on your use cases, for approximately 45 minutes.",
  "Puis-je demander une version d'essai ?":"Can I request a trial version?", "Oui, un environnement de démonstration peut être mis à votre disposition pour tester les principales fonctionnalités.":"Yes, a demo environment can be made available so you can test the main features.",
  "Nos experts sont à votre écoute pour vous accompagner.":"Our experts are ready to support you."
,
  "J’ai lu et j’accepte la":"I have read and accept the",
  "Cette page explique comment les informations transmises via le site I-TECH sont utilisées et protégées.":"This page explains how information submitted through the I-TECH website is used and protected.",
  "Information importante":"Important information",
  "Cette politique doit être validée par I-TECH avant sa publication définitive, notamment pour les durées de conservation et les éventuels prestataires traitant des données.":"This policy must be validated by I-TECH before final publication, particularly regarding retention periods and any service providers processing data.",
  "1. Responsable du traitement":"1. Data controller",
  "Les informations transmises via le site sont traitées par I-TECH SARL. Pour toute question relative à vos données personnelles ou à l'exercice de vos droits, vous pouvez écrire à contacts@i-techsarl.com.":"Information submitted through the website is processed by I-TECH SARL. For any question about your personal data or exercising your rights, you can write to contacts@i-techsarl.com.",
  "2. Données susceptibles d'être collectées":"2. Data that may be collected",
  "Lorsque vous utilisez le formulaire Contact / Démo, nous pouvons recueillir les informations que vous renseignez : nom, prénom, entreprise, fonction, adresse e-mail professionnelle, téléphone, pays, secteur d'activité, solutions souhaitées et contenu de votre message.":"When you use the Contact / Demo form, we may collect the information you provide: first and last name, company, position, business email address, phone number, country, business sector, solutions of interest and the content of your message.",
  "3. Finalités du traitement":"3. Purposes of processing",
  "Ces informations sont utilisées pour répondre à votre demande, organiser une démonstration, vous recontacter au sujet de votre projet et assurer le suivi de la relation avec I-TECH.":"This information is used to respond to your request, arrange a demonstration, contact you about your project and follow up on your relationship with I-TECH.",
  "4. Caractère obligatoire des informations":"4. Required information",
  "Les champs marqués d'un astérisque sont nécessaires au traitement de la demande. Les autres informations sont facultatives. Sans les informations obligatoires, I-TECH peut ne pas être en mesure de donner suite à la demande.":"Fields marked with an asterisk are required to process the request. Other information is optional. Without the required information, I-TECH may not be able to respond to the request.",
  "5. Destinataires des données":"5. Data recipients",
  "Les données sont destinées aux équipes I-TECH habilitées à traiter les demandes commerciales, techniques ou de support. Elles ne sont pas destinées à être vendues à des tiers.":"The data is intended for I-TECH teams authorized to handle commercial, technical or support requests. It is not intended to be sold to third parties.",
  "6. Durée de conservation":"6. Retention period",
  "Les données sont conservées pendant la durée nécessaire au traitement et au suivi de la demande, puis selon les durées applicables aux obligations administratives, contractuelles ou légales d'I-TECH. Les durées précises doivent être validées par I-TECH avant publication définitive.":"Data is retained for the time needed to process and follow up on the request, and then in accordance with periods applicable to I-TECH's administrative, contractual or legal obligations. Exact retention periods must be validated by I-TECH before final publication.",
  "7. Sécurité":"7. Security",
  "I-TECH met en œuvre des mesures organisationnelles et techniques adaptées afin de limiter l'accès non autorisé, la perte, l'altération ou la divulgation des données personnelles.":"I-TECH implements appropriate organizational and technical measures to limit unauthorized access, loss, alteration or disclosure of personal data.",
  "8. Vos droits":"8. Your rights",
  "Vous pouvez contacter I-TECH pour demander l'accès à vos données, leur rectification ou, lorsque les conditions applicables le permettent, leur suppression, leur limitation ou vous opposer à certains traitements.":"You may contact I-TECH to request access to your data, its correction or, where applicable conditions allow, its deletion or restriction, or to object to certain processing.",
  "9. Préférences et stockage local":"9. Preferences and local storage",
  "Le site peut utiliser le stockage local du navigateur pour mémoriser certaines préférences, notamment la langue choisie. Ces informations servent au fonctionnement et au confort de navigation du site.":"The website may use browser local storage to remember certain preferences, including the selected language. This information supports the website's operation and browsing convenience.",
  "10. Mise à jour de la politique":"10. Policy updates",
  "Cette politique peut évoluer afin de refléter les changements du site, des traitements ou des exigences applicables. La version publiée sur cette page est celle accessible aux visiteurs.":"This policy may evolve to reflect changes to the website, processing activities or applicable requirements. The version published on this page is the version available to visitors.",
  "Construisez votre avenir":"Build your future",
  "Grandissez avec I-TECH":"Grow with I-TECH",
  "Rejoignez des équipes qui conçoivent des solutions utiles, apprennent ensemble et accompagnent la transformation digitale de nos clients.":"Join teams that build useful solutions, learn together and support our clients' digital transformation.",
  "Trouvez votre prochaine opportunité":"Find your next opportunity",
  "Découvrez les opportunités actuellement présentées par I-TECH et trouvez celle qui correspond à votre profil.":"Explore the opportunities currently presented by I-TECH and find the one that matches your profile.",
  "Rechercher un poste, un métier ou un mot-clé":"Search for a role, profession or keyword",
  "Rechercher une opportunité":"Search opportunities",
  "Effacer la recherche":"Clear search",
  "opportunités disponibles":"opportunities available",
  "opportunité disponible":"opportunity available",
  "Aucune opportunité trouvée":"No opportunities found",
  "Essayez un autre mot-clé ou envoyez-nous une candidature spontanée.":"Try another keyword or send us a spontaneous application.",
  "Votre expérience I-TECH":"Your I-TECH experience",
  "Candidature spontanée":"Spontaneous application",
  "Une question sur vos données ?":"A question about your data?",
  "Contactez I-TECH à l'adresse suivante :":"Contact I-TECH at:",

};

type I18nValue = { lang: Language; setLang: (l: Language)=>void; t: (s:string)=>string };
const I18nContext = createContext<I18nValue>({ lang:"fr", setLang:()=>{}, t:(s)=>s });

const LANGUAGE_PREFERENCE_KEY = "itech-language-preference";

function getBrowserLanguage(): Language {
  if (typeof navigator === "undefined") return "fr";
  const browserLanguage = (navigator.languages?.[0] || navigator.language || "fr").toLowerCase();
  return browserLanguage.startsWith("en") ? "en" : "fr";
}

export function LanguageProvider({children}:{children:ReactNode}) {
  const [lang,setLangState] = useState<Language>(() => {
    const savedPreference = localStorage.getItem(LANGUAGE_PREFERENCE_KEY);
    if (savedPreference === "fr" || savedPreference === "en") return savedPreference;
    return getBrowserLanguage();
  });

  const setLang = (nextLanguage: Language) => {
    localStorage.setItem(LANGUAGE_PREFERENCE_KEY, nextLanguage);
    setLangState(nextLanguage);
  };

  useEffect(()=>{
    document.documentElement.lang = lang;
  },[lang]);

  const value=useMemo(()=>({lang,setLang,t:(s:string)=>lang==="en"?(EN[s]??s):s}),[lang]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}
export const useLanguage=()=>useContext(I18nContext);
