import { Injectable, signal } from '@angular/core';
export type Language = 'fr'|'en';
const EN: Record<string,string> = {
  'Accueil':'Home','Solutions':'Solutions','Secteurs':'Sectors','Ressources':'Resources',"L'Entreprise":'Company','Contact & Support':'Contact & Support',
  'Demander une démo':'Request a demo','Accélérez la':'Accelerate the','transformation digitale':'digital transformation','de votre institution financière.':'of your financial institution.',
  "I-TECH accompagne les banques, établissements de microfinance et entreprises avec des solutions Core Banking, Mobile Banking, Paiement Digital et Transformation Monétique adaptées aux réalités africaines.":'I-TECH supports banks, microfinance institutions and companies with Core Banking, Mobile Banking, Digital Payment and Card Transformation solutions adapted to African realities.',
  'Découvrir nos solutions':'Discover our solutions',"d'expertise":'of expertise','Conformité':'Compliance','Solutions déployées':'Solutions deployed','en Afrique':'in Africa','Support':'Support',
  'Gamme ALPHA':'ALPHA Range',
  'Des solutions conçues pour les institutions financières modernes':'Solutions designed for modern financial institutions',
  "Une suite logicielle complète pour digitaliser vos opérations, renforcer votre conformité et améliorer l'expérience client.":'A complete software suite to digitize operations, strengthen compliance and improve customer experience.',
  'En savoir plus':'Learn more',
  'Une expertise adaptée à chaque secteur':'Expertise tailored to every sector',
  'Microfinance':'Microfinance','Banques':'Banks','Grandes entreprises':'Large enterprises',
  "Maîtrisez les coûts opérationnels et améliorez l'expérience client.":'Control operating costs and improve the customer experience.',
  'Modernisez vos systèmes et réinventez vos services digitaux.':'Modernize your systems and reinvent your digital services.',
  'Automatisez vos processus financiers et de gestion.':'Automate your financial and management processes.',
  'Focus métier':'Business focus','Diagnostic SI':'IT assessment','Déploiement':'Deployment','Accompagnement':'Support',
  'Nos partenaires':'Our partners','Ils nous font confiance':'They trust us','Rejoignez plus de':'Join more than','250 institutions':'250 institutions','qui ont choisi I-TECH pour leur transformation digitale.':'that chose I-TECH for their digital transformation.','Partenaire I-TECH · institution financière':'I-TECH partner · financial institution','Visiter le site':'Visit website','Visiter':'Visit','Et plus de':'And more than','250 autres institutions':'250 other institutions',"à travers l'Afrique":'across Africa','Voir tous nos partenaires':'See all our partners',
  'Des résultats qui parlent':'Results that speak for themselves',
  "Des indicateurs concrets qui reflètent notre accompagnement des institutions financières en Afrique.":'Concrete indicators that reflect our support for financial institutions across Africa.',
  "Années d'expérience":'Years of experience','Institutions accompagnées':'Institutions supported','Pays en Afrique':'Countries in Africa','Utilisateurs finaux':'End users','Transactions par an':'Transactions per year',
  'Nos clients':'Our clients','Ils nous font':'They put their','confiance':'trust in us',
  'Des institutions financières, entreprises et organisations qui avancent avec nous depuis plus de 19 ans.':'Financial institutions, companies and organizations moving forward with us for over 19 years.',
  'Clients de confiance':'Trusted clients',
  'Pourquoi I-TECH':'Why I-TECH','Un partenaire technologique de confiance':'A trusted technology partner',
  'Cliquez sur une fenêtre pour découvrir chaque engagement.':'Click a window to discover each commitment.',
  'Expertise métier':'Business expertise','Une connaissance approfondie des métiers financiers.':'In-depth knowledge of financial services.',
  'Une assistance réactive et personnalisée.':'Responsive, personalized assistance.',
  'Aux normes COBAC, BEAC et internationales.':'Compliant with COBAC, BEAC and international standards.',
  'Intégration':'Integration','Compatible avec votre écosystème existant.':'Compatible with your existing ecosystem.',
  'Sécurité':'Security','Des données protégées à chaque étape.':'Data protected at every stage.',
  'Innovation':'Innovation','Des solutions évolutives pour demain.':'Scalable solutions for tomorrow.',
  'Ouvrir':'Open',
  'Prêt à accélérer votre transformation digitale ?':'Ready to accelerate your digital transformation?',
  'Échangez avec nos experts et découvrez comment I-TECH peut vous accompagner.':'Talk with our experts and discover how I-TECH can support you.',
  'Demander une démonstration':'Request a demo',
  'Contactez un expert':'Contact an expert','Précédent':'Previous','Suivant':'Next',
  'Voir tous nos clients':'View all our clients','Confiance':'Trust','Des partenariats solides':'Strong partnerships',
  'Performance':'Performance','Des résultats concrets':'Tangible results','Croissance':'Growth','Un développement partagé':'Shared development',
  'Toujours plus loin ensemble':'Going further together','Tous nos clients':'All our clients',
  'NOS CLIENTS':'OUR CLIENTS','Tous ceux qui nous font':'Everyone who puts their',
  'Découvrez les institutions et organisations qui accompagnent l’écosystème I-TECH.':'Discover the institutions and organizations in the I-TECH ecosystem.',
  'Fermer':'Close',
  'À propos':'About us' ,'Carrières':'Careers','Partenaires':'Partners','Contact / Démo':'Contact / Demo','Support Client':'Customer Support','Politique de confidentialité':'Privacy Policy',
  'Support disponible':'24/7 support','Présence régionale':'Regional presence',
  'Un écosystème intégré pour couvrir tous vos besoins métier':'An integrated ecosystem covering all your business needs',
  'Gestion complète des opérations bancaires et financières':'Complete management of banking and financial operations',
  'Digitalisez vos encaissements et rapprochements terrain':'Digitize your field collections and reconciliations',
  'Services digitaux & mobiles pour vous démarquer de vos concurrents':'Digital & mobile services to stand out from your competitors',
  "Gérez efficacement vos talents, la paie et l'administration du personnel":'Efficiently manage your talent, payroll and personnel administration',
  'Déclarations réglementaires et reporting bancaire':'Regulatory declarations and banking reporting',
  'Une suite complète et intégrée':'A complete and integrated suite',
  'Prêt à transformer votre institution ?': 'Ready to transform your institution?',
  'Échangez avec nos experts et découvrez la solution la plus adaptée à vos besoins.': 'Talk with our experts and discover the solution best suited to your needs.',
  'Échange avec nos experts': 'Discussion with our experts',
  'Solution ALPHA': 'ALPHA Solution',
  'La plateforme bancaire qui centralise toutes vos opérations.': 'The banking platform that centralizes all your operations.',
  'Gérez les comptes, crédits, épargne, opérations de caisse et reporting depuis une plateforme unique, sécurisée et évolutive.': 'Manage accounts, loans, savings, cash operations and reporting from one secure and scalable platform.',
  'Une architecture complète et intégrée': 'A complete and integrated architecture',
  'Gestion bancaire complète': 'Complete banking management',
  'Solutions adaptées aux EMF': 'Solutions tailored to microfinance institutions',
  'Comptabilité intégrée et reporting': 'Integrated accounting and reporting',
  'Émission de cartes et transactions': 'Card issuance and transactions',
  'Fonctionnalités clés': 'Key features',
  'Captures d’écran': 'Screenshots',
  'Tableau de bord': 'Dashboard',
  'Comptes': 'Accounts',
  'Reporting': 'Reporting',
  'Voir plus de captures': 'View more screenshots',
  'Gestion des comptes': 'Account management',
  'Gestion du crédit': 'Credit management',
  "Gestion de l'épargne": 'Savings management',
  'Gestion des agences': 'Branch management',
  'Reporting & BI': 'Reporting & BI',
  'Créez et administrez comptes courants, épargne et comptes professionnels depuis un référentiel client unique.': 'Create and manage current, savings and business accounts from a single customer repository.',
  'Instruisez, octroyez et suivez les crédits avec échéanciers, garanties et relances automatiques.': 'Process, grant and monitor loans with schedules, guarantees and automated reminders.',
  "Proposez des produits d'épargne souples, avec intérêts calculés automatiquement et relevés détaillés.": 'Offer flexible savings products with automatically calculated interest and detailed statements.',
  'Pilotez votre réseau multi-agences : caisses, utilisateurs, habilitations et consolidations.': 'Manage your multi-branch network: cash desks, users, permissions and consolidation.',
  'Exploitez tableaux de bord et états de pilotage pour décider vite, sur des données fiables.': 'Use dashboards and management reports to make fast decisions based on reliable data.',
  'Les bénéfices pour votre institution': 'Benefits for your institution',
  'Centralisation des opérations': 'Centralized operations',
  'Fiabilité et sécurité': 'Reliability and security',
  'Conformité réglementaire': 'Regulatory compliance',
  'Gain de temps et productivité': 'Time savings and productivity',
  'Meilleure prise de décision': 'Better decision-making',
  'Core Banking · ALPHA': 'Core Banking · ALPHA',
  'Découvrez comment ALPHA peut transformer la gestion de votre institution.': 'Discover how ALPHA can transform the management of your institution.',
  "Échangez avec nos experts pour découvrir comment la suite ALPHA peut s'adapter à votre institution.": 'Talk with our experts to discover how the ALPHA suite can adapt to your institution.',
  'Solution I-COLLECT': 'I-COLLECT Solution',
  'Collecte Journalière': 'Daily Collection',
  'Digitalisez vos encaissements et rapprochez-vous de vos clients.': 'Digitize your collections and get closer to your customers.',
  'I-Collect simplifie la collecte terrain, sécurise les opérations et améliore le suivi des collecteurs en temps réel.': 'I-Collect simplifies field collection, secures operations and improves real-time collector monitoring.',
  'Une solution complète pour la collecte terrain': 'A complete solution for field collection',
  'Collecte sur le terrain': 'Field collection',
  'Synchronisation en temps réel': 'Real-time synchronization',
  'Suivi & contrôle des équipes': 'Team monitoring & control',
  'Rapprochement comptable': 'Accounting reconciliation',
  'Commissions automatisées': 'Automated commissions',
  "De l'encaissement terrain au rapprochement comptable, pilotez l'ensemble du processus depuis une solution intégrée.": 'From field collection to accounting reconciliation, manage the entire process from one integrated solution.',
  'Gestion des collecteurs et tournées': 'Collector and route management',
  'Encaissements sécurisés (POS & Mobile)': 'Secure collections (POS & Mobile)',
  'Reçus électroniques instantanés': 'Instant electronic receipts',
  'Suivi en temps réel des activités': 'Real-time activity monitoring',
  'Gestion des accréditations': 'Accreditation management',
  'Calcul automatique des commissions': 'Automatic commission calculation',
  'I-Collect Admin pour les managers': 'I-Collect Admin for managers',
  'Application épargnant: MyCollect': 'Saver application: MyCollect',
  'Tournée du jour': "Today's route",
  'Encaisser': 'Collect payment',
  'Solde total': 'Total balance',
  'Efficacité opérationnelle': 'Operational efficiency',
  'Sécurité renforcée': 'Enhanced security',
  'Meilleur contrôle des équipes': 'Better team control',
  'Expérience client améliorée': 'Improved customer experience',
  'Augmentation de la rentabilité': 'Increased profitability',
  'Digitalisez votre collecte journalière dès aujourd’hui.': 'Digitize your daily collection today.',
  'Échangez avec nos experts et découvrez comment I-COLLECT peut sécuriser et simplifier vos opérations de collecte.': 'Talk with our experts and discover how I-COLLECT can secure and simplify your collection operations.',
  'Solution Digital & Mobile': 'Digital & Mobile Solution',
  'Offrez une expérience bancaire digitale fluide et sécurisée.': 'Deliver a seamless and secure digital banking experience.',
  "Alpha Mobile Banking et les services digitaux I-TECH permettent à vos clients d'accéder à leurs services 24h/24 et 7j/7.": 'Alpha Mobile Banking and I-TECH digital services allow your customers to access their services 24/7.',
  'Une expérience digitale complète': 'A complete digital experience',
  'Mobile Banking': 'Mobile Banking',
  'Portails Clients': 'Customer Portals',
  'Paiements Digitaux': 'Digital Payments',
  'Notifications & Alertes': 'Notifications & Alerts',
  'Sécurité Avancée': 'Advanced Security',
};
@Injectable({providedIn:'root'})
export class LanguageService {
  lang = signal<Language>(this.initial());
  private initial():Language { const s=localStorage.getItem('itech-language-preference'); if(s==='fr'||s==='en') return s; return navigator.language.toLowerCase().startsWith('en')?'en':'fr'; }
  toggle(){ const n=this.lang()==='fr'?'en':'fr'; localStorage.setItem('itech-language-preference',n); this.lang.set(n); }
  t(s:string){ return this.lang()==='en' ? (EN[s] ?? s) : s; }
}
